In [1]:
import sqlite3
import pandas as pd
from pandas.io import sql
import numpy as np

In [2]:
filename="singapore-airbnb/listings.csv"
o_df = pd.read_csv(filename)


In [3]:
o_df.head(10)

id                                     name  host_id  host_name  \
0   49091        COZICOMFORT LONG TERM STAY ROOM 2   266763  Francesca   
1   50646          Pleasant Room along Bukit Timah   227796    Sujatha   
2   56334                              COZICOMFORT   266763  Francesca   
3   71609      Ensuite Room (Room 1 & 2) near EXPO   367042    Belinda   
4   71896          B&B  Room 1 near Airport & EXPO   367042    Belinda   
5   71903               Room 2-near Airport & EXPO   367042    Belinda   
6   71907         3rd level Jumbo room 5 near EXPO   367042    Belinda   
7  241503   Long stay at The Breezy East "Leopard"  1017645     Bianca   
8  241508  Long stay at The Breezy East "Plumeria"  1017645     Bianca   
9  241510  Long stay at The Breezy East "Red Palm"  1017645     Bianca   

  neighbourhood_group neighbourhood  latitude  longitude     room_type  price  \
0        North Region     Woodlands   1.44255  103.79580  Private room     83   
1      Central Region   Bukit Timah   1.33235  103.78521  Private room     81   
2        North Region     Woodlands   1.44246  103.79667  Private room     69   
3         East Region      Tampines   1.34541  103.95712  Private room    206   
4         East Region      Tampines   1.34567  103.95963  Private room     94   
5         East Region      Tampines   1.34702  103.96103  Private room    104   
6         East Region      Tampines   1.34348  103.96337  Private room    208   
7         East Region         Bedok   1.32304  103.91363  Private room     50   
8         East Region         Bedok   1.32458  103.91163  Private room     54   
9         East Region         Bedok   1.32461  103.91191  Private room     42   

   minimum_nights  number_of_reviews last_review  reviews_per_month  \
0             180                  1  2013-10-21               0.01   
1              90                 18  2014-12-26               0.28   
2               6                 20  2015-10-01               0.20   
3               1                 14  2019-08-11               0.15   
4               1                 22  2019-07-28               0.22   
5               1                 39  2019-08-15               0.38   
6               1                 25  2019-07-25               0.25   
7              90                174  2019-05-31               1.88   
8              90                198  2019-04-28               2.08   
9              90                236  2019-07-31               2.53   

   calculated_host_listings_count  availability_365  
0                               2               365  
1                               1               365  
2                               2               365  
3                               9               353  
4                               9               355  
5                               9               346  
6                               9               172  
7                               4                59  
8                               4               133  
9                               4               147

In [3]:
o_df = o_df.fillna(0)

In [6]:
o_df['last_review'].unique()

array(['2013-10-21', '2014-12-26', '2015-10-01', ..., '2019-04-09',
       '2019-06-17', '2019-03-22'], dtype=object)

In [7]:
o_df

id                                               name    host_id  \
0        49091                  COZICOMFORT LONG TERM STAY ROOM 2     266763   
1        50646                    Pleasant Room along Bukit Timah     227796   
2        56334                                        COZICOMFORT     266763   
3        71609                Ensuite Room (Room 1 & 2) near EXPO     367042   
4        71896                    B&B  Room 1 near Airport & EXPO     367042   
5        71903                         Room 2-near Airport & EXPO     367042   
6        71907                   3rd level Jumbo room 5 near EXPO     367042   
7       241503             Long stay at The Breezy East "Leopard"    1017645   
8       241508            Long stay at The Breezy East "Plumeria"    1017645   
9       241510            Long stay at The Breezy East "Red Palm"    1017645   
10      275343  Conveniently located City Room!( (Phone number...    1439258   
11      275344              15 mins to Outram MRT Single Room (B)    1439258   
12      289234                             Booking for 3 bedrooms     367042   
13      294281                     5 mins walk from Newton subway    1521514   
14      324945                 20 Mins to Sentosa @ Hilltop ! (8)    1439258   
15      330089             Accomo@ REDHILL-INSEAD, NTU,NUS -Mu(D)    1439258   
16      330095       10 mins to Redhill MRT @ Mini Orange Room(5)    1439258   
17      344803                  Budget short stay room near  EXPO     367042   
18      355955    Double room in an Authentic Peranakan Shophouse    1759905   
19      369141                    5mins from Newton Train Station    1521514   
20      369145                        5 mins walk from Newton MRT    1521514   
21      395191               Heritage Apartment Room near Orchard    1975201   
22      423875                    Master Bedroom 4-Airport & EXPO     367042   
23      481789                 Master Bedroom in Newly Built Flat    2386154   
24      553229              Comfortable Condo Room - Boon Lay MRT    1030128   
25      604966                  Boutique 1 bedroom entiere appart    2996022   
26      642660                 BEST CITY LIVING WITH GA RESIDENCE    3212572   
27      696136              Quiet ensuite room in Holland Village    1289033   
28      719944                HDB housing in prime area near town    3648224   
29      733863                              Homestay at Serangoon    3824517   
...        ...                                                ...        ...   
7877  38035527    Modern Loft (3 Mins to MRT) - (Retractable Bed)    6632570   
7878  38035715                           10 reason to book-studio   32184450   
7879  38035791                          10 reason to stay -studio   32184450   
7880  38036353       Common room at Orchard/Somerset/Central area  262337792   
7881  38047765   Spacious resort living with private balcony/pond    7532643   
7882  38049336   Lavender Queenbed Rm Heritage windows: 5mwalkMRT    8948251   
7883  38049380            免费机场接机,5分钟步行滨海湾广场鱼尾狮公园,1分钟步行地铁站,周边设施齐全,  228823978   
7884  38049946  Oriental Holiday Hotel Style 1 BR Condo at Orc...   43591543   
7885  38050260             Soho living at the Clarke Quay Central   57336779   
7886  38050827  Tampines mrt 3 min away/near airport/ 3 month ...  259978610   
7887  38051818          Cozy loft studio apartment bedroom unit .  153045562   
7888  38057160  Ensuite room in quiet estate in Ang Mo Kio nr MRT  122219616   
7889  38061740  Compact apartment near supermarket/mrt/bus/foo...    1725521   
7890  38077716  Luxurious stay , 3 bedroom apartment at Orchar...  238891646   
7891  38078117            Cozy Unit Nearby Orchard and Ting Bahru  288249975   
7892  38080105  Luxury 1-bed condo unit in the heart of Marina...   10823332   
7893  38086911                           Comfortable House Studio  108818897   
7894  38087310             Convenient Loft Space in Pasir Panjang  108818897   
7895  380876

In [12]:
higher_b = o_df["price"].quantile(0.99)
lower_b = o_df["price"].quantile(0.005)

m_df = o_df[o_df['price'] <=higher_b]
df = m_df[m_df['price'] >= lower_b].copy()

In [117]:
df['price'].unique()

array([ 83,  81,  69, 206,  94, 104, 208,  50,  54,  42,  44,  40, 417,
        65,  31,  49,  60,  56,  37,  53, 276, 167, 100,  26, 176, 165,
        51, 128, 300, 150, 200, 278, 243,  35, 219,  76, 140,  72, 231,
       190, 319, 149, 240, 137,  58, 129, 400, 131,  67, 217,  82,  89,
        90, 194, 550,  85,  33, 169, 160, 260,  68, 118, 221, 360, 381,
        64, 250,  99, 139, 281,  87,  32, 342, 253, 303, 135, 462, 119,
       500, 108,  36,  93, 106,  25, 110, 228, 254, 275, 125,  92, 126,
       181,  57,  86, 179, 237, 199, 158, 122, 244, 156,  29,  78, 387,
        62, 358, 115, 306, 218, 249, 268,  79, 258, 164,  28, 224, 201,
       287,  75, 168, 146, 132, 269,  19, 215,  46, 186, 144, 229, 390,
       154, 650, 107, 350, 111, 628,  61, 175, 121,  43, 182, 112, 189,
       197, 304, 222,  71, 239, 151,  74, 235, 490, 153, 187, 171, 450,
       344,  39, 210, 681,  22, 308, 408, 325, 161, 315, 310, 286, 750,
       292, 256, 432, 103,  97, 178, 475, 312, 415, 449,  96, 12

In [118]:
df.head()

id                                 name  host_id  host_name  \
0  49091    COZICOMFORT LONG TERM STAY ROOM 2   266763  Francesca   
1  50646      Pleasant Room along Bukit Timah   227796    Sujatha   
2  56334                          COZICOMFORT   266763  Francesca   
3  71609  Ensuite Room (Room 1 & 2) near EXPO   367042    Belinda   
4  71896      B&B  Room 1 near Airport & EXPO   367042    Belinda   

  neighbourhood_group neighbourhood  latitude  longitude     room_type  price  \
0        North Region     Woodlands   1.44255  103.79580  Private room     83   
1      Central Region   Bukit Timah   1.33235  103.78521  Private room     81   
2        North Region     Woodlands   1.44246  103.79667  Private room     69   
3         East Region      Tampines   1.34541  103.95712  Private room    206   
4         East Region      Tampines   1.34567  103.95963  Private room     94   

   minimum_nights  number_of_reviews last_review  reviews_per_month  \
0             180                  1  2013-10-21               0.01   
1              90                 18  2014-12-26               0.28   
2               6                 20  2015-10-01               0.20   
3               1                 14  2019-08-11               0.15   
4               1                 22  2019-07-28               0.22   

   calculated_host_listings_count  availability_365  
0                               2               365  
1                               1               365  
2                               2               365  
3                               9               353  
4                               9               355

In [119]:
df["neighbourhood_group"].unique()

array(['North Region', 'Central Region', 'East Region', 'West Region',
       'North-East Region'], dtype=object)

In [13]:
df.drop("id", axis=1,inplace=True)


In [14]:
df.drop("host_name", axis=1,inplace=True)

In [15]:
df.drop("last_review", axis=1,inplace=True)

In [16]:
df.drop("name", axis=1,inplace=True)

In [124]:
df.drop("host_id", axis=1,inplace=True)

/home/jingcheng/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [9]:
df.head(5)

host_id neighbourhood_group neighbourhood  latitude  longitude  \
0   266763        North Region     Woodlands   1.44255  103.79580   
1   227796      Central Region   Bukit Timah   1.33235  103.78521   
2   266763        North Region     Woodlands   1.44246  103.79667   
3   367042         East Region      Tampines   1.34541  103.95712   
4   367042         East Region      Tampines   1.34567  103.95963   

      room_type  price  minimum_nights  number_of_reviews  reviews_per_month  \
0  Private room     83             180                  1               0.01   
1  Private room     81              90                 18               0.28   
2  Private room     69               6                 20               0.20   
3  Private room    206               1                 14               0.15   
4  Private room     94               1                 22               0.22   

   calculated_host_listings_count  availability_365  
0                               2               365  
1                               1               365  
2                               2               365  
3                               9               353  
4                               9               355

In [126]:
df["room_type"].unique()

array(['Private room', 'Entire home/apt', 'Shared room'], dtype=object)

In [127]:
df["neighbourhood"].unique()

array(['Woodlands', 'Bukit Timah', 'Tampines', 'Bedok', 'Bukit Merah',
       'Newton', 'Geylang', 'River Valley', 'Jurong West', 'Rochor',
       'Queenstown', 'Serangoon', 'Marine Parade', 'Pasir Ris',
       'Toa Payoh', 'Outram', 'Punggol', 'Tanglin', 'Hougang', 'Kallang',
       'Novena', 'Downtown Core', 'Bukit Panjang', 'Singapore River',
       'Orchard', 'Ang Mo Kio', 'Bukit Batok', 'Museum', 'Sembawang',
       'Choa Chu Kang', 'Central Water Catchment', 'Sengkang', 'Clementi',
       'Jurong East', 'Bishan', 'Yishun', 'Mandai', 'Southern Islands',
       'Sungei Kadut', 'Western Water Catchment', 'Marina South',
       'Lim Chu Kang'], dtype=object)

In [17]:
neighbours = list(df["neighbourhood"].unique())
neighbours_dict = {}
for i in range(len(neighbours)):
    neighbours_dict[neighbours[i]] = i
neighbours_dict

{'Woodlands': 0,
 'Bukit Timah': 1,
 'Tampines': 2,
 'Bedok': 3,
 'Bukit Merah': 4,
 'Newton': 5,
 'Geylang': 6,
 'River Valley': 7,
 'Jurong West': 8,
 'Rochor': 9,
 'Queenstown': 10,
 'Serangoon': 11,
 'Marine Parade': 12,
 'Pasir Ris': 13,
 'Toa Payoh': 14,
 'Outram': 15,
 'Punggol': 16,
 'Tanglin': 17,
 'Hougang': 18,
 'Kallang': 19,
 'Novena': 20,
 'Downtown Core': 21,
 'Bukit Panjang': 22,
 'Singapore River': 23,
 'Orchard': 24,
 'Ang Mo Kio': 25,
 'Bukit Batok': 26,
 'Museum': 27,
 'Sembawang': 28,
 'Choa Chu Kang': 29,
 'Central Water Catchment': 30,
 'Sengkang': 31,
 'Clementi': 32,
 'Jurong East': 33,
 'Bishan': 34,
 'Yishun': 35,
 'Mandai': 36,
 'Southern Islands': 37,
 'Sungei Kadut': 38,
 'Western Water Catchment': 39,
 'Marina South': 40,
 'Lim Chu Kang': 41}

In [18]:
room_types = []
for index, row in df.iterrows():
    if row['room_type'] == "Private room":
        room_types.append(0)
    elif row['room_type'] == "Entire home/apt":
        room_types.append(1)
    else:
        room_types.append(2)
df["room_type"] = room_types

In [19]:
neighbourhood_groups = []
for index, row in df.iterrows():
    if row['neighbourhood_group'] == "North Region":
        neighbourhood_groups.append(0)
    elif row['neighbourhood_group'] == "Central Region":
        neighbourhood_groups.append(1)
    elif row['neighbourhood_group'] == "East Region":
        neighbourhood_groups.append(2)
    elif row['neighbourhood_group'] == "West Region":
        neighbourhood_groups.append(3)
    else:
        neighbourhood_groups.append(4)
df["neighbourhood_group"] = neighbourhood_groups

In [20]:
neighbour_types = []
for index, row in df.iterrows():
        neighbour_types.append(neighbours_dict[row["neighbourhood"]])
df["neighbourhood"] = neighbour_types

In [21]:
from sklearn import datasets
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
import pandas as pd
from sklearn.model_selection import train_test_split


/home/jingcheng/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [22]:
import numpy as np
df.dropna(how="all")

host_id  neighbourhood_group  neighbourhood  latitude  longitude  \
0        266763                    0              0   1.44255  103.79580   
1        227796                    1              1   1.33235  103.78521   
2        266763                    0              0   1.44246  103.79667   
3        367042                    2              2   1.34541  103.95712   
4        367042                    2              2   1.34567  103.95963   
5        367042                    2              2   1.34702  103.96103   
6        367042                    2              2   1.34348  103.96337   
7       1017645                    2              3   1.32304  103.91363   
8       1017645                    2              3   1.32458  103.91163   
9       1017645                    2              3   1.32461  103.91191   
10      1439258                    1              4   1.28875  103.80814   
11      1439258                    1              4   1.28837  103.81099   
12       367042                    2              2   1.34561  103.95984   
13      1521514                    1              5   1.31125  103.83816   
14      1439258                    1              4   1.28976  103.80896   
15      1439258                    1              4   1.28677  103.81244   
16      1439258                    1              4   1.28537  103.81087   
17       367042                    2              2   1.34943  103.95951   
18      1759905                    1              6   1.31420  103.90232   
19      1521514                    1              5   1.31150  103.83759   
20      1521514                    1              5   1.31159  103.83805   
21      1975201                    1              7   1.29345  103.83562   
22       367042                    2              2   1.34838  103.95920   
23      2386154                    2              2   1.34816  103.93238   
24      1030128                    3              8   1.34135  103.71139   
25      2996022                    1              1   1.33171  103.79383   
26      3212572                    1              9   1.30109  103.85234   
27      1289033                    1              1   1.31016  103.79853   
28      3648224                    1             10   1.30901  103.79639   
29      3824517                    4             11   1.36743  103.87288   
...         ...                  ...            ...       ...        ...   
7876    8948251                    1             19   1.31163  103.86090   
7877    6632570                    0              0   1.44052  103.79784   
7878   32184450                    1              6   1.31468  103.89816   
7879   32184450                    1              6   1.31574  103.89829   
7880  262337792                    1              7   1.29560  103.83803   
7881    7532643                    1              4   1.28474  103.82882   
7882    8948251                    1             19   1.31004  103.86208   
7883  228823978                    1             21   1.27875  103.85505   
7884   43591543                    1              7   1.29820  103.83444   
7885   57336779                    1             23   1.28942  103.84548   
7886  259978610                    2              2   1.35556  103.94428   
7887  153045562                    1             19   1.30329  103.86155   
7888  122219616                    4             25   1.37398  103.83906   
7889    1725521                    1              6   1.31413  103.88857   
7891  288249975                    1             17   1.29481  103.82840   
7892   10823332                    1             21   1.28161  103.85350   
7893  108818897                    1             10   1.28111  103.78636   
7894  108818897                    1             10   1.28129  103.78607   
7895  108818897                    1             10   1.28001  103.78737   
7896    8200399                    1              6   1.31557  103.88979   
7897  262337792                    1              7   1.

In [23]:
for column in df.columns:
    df[column] = pd.to_numeric(df[column])

In [136]:
df

neighbourhood_group  neighbourhood  latitude  longitude  room_type  \
0                       0              0   1.44255  103.79580          0   
1                       1              1   1.33235  103.78521          0   
2                       0              0   1.44246  103.79667          0   
3                       2              2   1.34541  103.95712          0   
4                       2              2   1.34567  103.95963          0   
5                       2              2   1.34702  103.96103          0   
6                       2              2   1.34348  103.96337          0   
7                       2              3   1.32304  103.91363          0   
8                       2              3   1.32458  103.91163          0   
9                       2              3   1.32461  103.91191          0   
10                      1              4   1.28875  103.80814          0   
11                      1              4   1.28837  103.81099          0   
12                      2              2   1.34561  103.95984          0   
13                      1              5   1.31125  103.83816          0   
14                      1              4   1.28976  103.80896          0   
15                      1              4   1.28677  103.81244          0   
16                      1              4   1.28537  103.81087          0   
17                      2              2   1.34943  103.95951          0   
18                      1              6   1.31420  103.90232          0   
19                      1              5   1.31150  103.83759          0   
20                      1              5   1.31159  103.83805          0   
21                      1              7   1.29345  103.83562          0   
22                      2              2   1.34838  103.95920          0   
23                      2              2   1.34816  103.93238          0   
24                      3              8   1.34135  103.71139          0   
25                      1              1   1.33171  103.79383          1   
26                      1              9   1.30109  103.85234          0   
27                      1              1   1.31016  103.79853          0   
28                      1             10   1.30901  103.79639          2   
29                      4             11   1.36743  103.87288          0   
...                   ...            ...       ...        ...        ...   
7876                    1             19   1.31163  103.86090          0   
7877                    0              0   1.44052  103.79784          0   
7878                    1              6   1.31468  103.89816          1   
7879                    1              6   1.31574  103.89829          1   
7880                    1              7   1.29560  103.83803          0   
7881                    1              4   1.28474  103.82882          1   
7882                    1             19   1.31004  103.86208          0   
7883                    1             21   1.27875  103.85505          1   
7884                    1              7   1.29820  103.83444          1   
7885                    1             23   1.28942  103.84548          1   
7886                    2              2   1.35556  103.94428          0   
7887                    1             19   1.30329  103.86155          0   
7888                    4             25   1.37398  103.83906          0   
7889                    1              6   1.31413  103.88857          1   
7891                    1             17   1.29481  103.82840          1   
7892                    1             21   1.28161  103.85350          1   
7893                    1             10   1.28111  103.78636          1   
7894                    1             10   1.28129  103.78607          1   
7895                    1             10   1.28001  103.78737          1   
7896                    1              6   1.31557  103.88979          0   
7897                    1              7   1.29482  10

In [24]:
X = df.drop("price",axis=1).values
y = df["price"].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=66)

In [25]:
from sklearn.linear_model import LinearRegression,BayesianRidge
model = RandomForestRegressor(n_estimators=110, max_depth=10)
model.fit(X_train,y_train)
preds = model.predict(X_test)

In [26]:
preds

array([240.15634812,  49.11483424, 336.15425807, ...,  29.8335934 ,
       153.89331239,  92.6678601 ])

In [235]:
y_test

array([287,  90, 410, ...,  49,  99,  51])

In [27]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,preds)

5729.225020480518

In [237]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)
preds = model.predict(X_test)

In [238]:
list(preds)

[190.01396483213193,
 80.02398732419624,
 202.7299880637711,
 168.16420086804374,
 174.3521723515496,
 141.5777778849615,
 121.70600699620718,
 110.21608845230185,
 108.7941686268814,
 134.27339738131104,
 237.12278036997486,
 111.18413680206777,
 177.25992286074688,
 95.11381145740324,
 134.33191101114335,
 44.857454665369914,
 122.77125120182063,
 58.45054060689654,
 171.12854094626164,
 89.1471310934894,
 198.63027151949336,
 186.0877381977225,
 221.54960153568481,
 147.00973369769054,
 206.29125995603135,
 82.11640124826681,
 153.43000185241,
 133.33372482850154,
 181.62041148575827,
 135.0294741211883,
 117.90324069208236,
 176.61285684328413,
 102.50189321699872,
 183.2597272570456,
 93.51266454021152,
 144.60632302467548,
 166.18212219185898,
 78.34747555603099,
 152.41703620130284,
 106.16932538943547,
 169.1821272081279,
 136.53035873655335,
 197.3076769230047,
 203.44636191466998,
 134.24949317049777,
 179.49990825383156,
 91.47758044050988,
 122.24307477405819,
 192.99621245

In [239]:
mean_squared_error(y_test,preds)

10378.186513092278

In [255]:
yl = list(y_test)
pl = list(preds)
for i in range(len(yl)):
    print((yl[i],pl[i]))

(287, 252.2)
(90, 233.4)
(410, 121.6)
(137, 161.8)
(131, 266.8)
(69, 57.6)
(99, 71.6)
(110, 171.4)
(56, 214.8)
(87, 121.4)
(24, 20.8)
(90, 99.2)
(146, 168.0)
(58, 97.0)
(153, 112.8)
(26, 139.6)
(40, 59.2)
(31, 106.6)
(160, 101.8)
(40, 299.8)
(444, 336.8)
(694, 61.2)
(26, 99.0)
(94, 90.8)
(131, 181.6)
(37, 63.8)
(69, 63.8)
(144, 158.6)
(135, 175.2)
(115, 113.0)
(175, 135.4)
(126, 244.8)
(139, 125.8)
(287, 204.2)
(51, 56.2)
(178, 158.8)
(200, 171.2)
(56, 216.0)
(164, 108.6)
(74, 99.0)
(100, 174.4)
(42, 65.6)
(231, 295.6)
(137, 154.2)
(153, 118.6)
(360, 324.6)
(58, 280.2)
(44, 59.2)
(96, 107.6)
(190, 155.8)
(250, 160.8)
(115, 194.2)
(240, 314.0)
(58, 53.6)
(119, 89.2)
(50, 66.6)
(499, 202.4)
(181, 146.2)
(206, 233.4)
(56, 56.0)
(81, 205.0)
(306, 357.8)
(550, 444.6)
(160, 160.2)
(168, 167.0)
(331, 94.4)
(144, 194.4)
(119, 132.4)
(129, 115.0)
(69, 133.0)
(110, 187.8)
(287, 226.2)
(210, 240.8)
(75, 69.0)
(44, 48.0)
(150, 187.0)
(119, 72.6)
(90, 88.0)
(32, 32.0)
(167, 116.2)
(99, 119.2)
(65, 

In [241]:
from sklearn.linear_model import LinearRegression,BayesianRidge
model = BayesianRidge()
model.fit(X_train,y_train)
preds = model.predict(X_test)

In [242]:
preds

array([190.68731894,  85.38051585, 200.88493814, ..., 209.38928429,
       147.91604792,  85.35849206])

In [243]:
mean_squared_error(y_test,preds)

10479.80227956605

In [244]:
from sklearn.linear_model import  LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)
preds = model.predict(X_test)

In [245]:
preds

array([360, 200, 360, ..., 200, 200, 200])

In [246]:
mean_squared_error(y_test,preds)

23733.609538580844

In [247]:
X_train

array([[6.32072700e+07, 0.00000000e+00, 3.50000000e+01, ...,
        6.00000000e-02, 1.00000000e+00, 3.65000000e+02],
       [1.63757139e+08, 2.00000000e+00, 3.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 3.65000000e+02],
       [2.08749650e+07, 1.00000000e+00, 1.20000000e+01, ...,
        3.18000000e+00, 8.00000000e+00, 4.20000000e+01],
       ...,
       [1.47720250e+07, 4.00000000e+00, 3.10000000e+01, ...,
        4.00000000e-02, 2.00000000e+00, 3.65000000e+02],
       [4.33157700e+07, 1.00000000e+00, 4.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [4.99084520e+07, 3.00000000e+00, 8.00000000e+00, ...,
        2.00000000e-02, 1.00000000e+00, 0.00000000e+00]])

In [248]:
from sklearn.ensemble import GradientBoostingRegressor
model = GradientBoostingRegressor(n_estimators=110, max_depth=10)
model.fit(X_train,y_train)
preds = model.predict(X_test)

In [249]:
preds

array([241.14706272,  51.83488116, 337.21328034, ...,  33.3256943 ,
       165.88531261,  92.43698889])

In [250]:
y_test

array([287,  90, 410, ...,  49,  99,  51])

In [251]:
mean_squared_error(y_test,preds)

5646.588269145283

In [28]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=5)
model.fit(X_train,y_train)
preds = model.predict(X_test)

In [253]:
preds

array([252.2, 233.4, 121.6, ...,  29.4, 129.6, 113. ])

In [29]:
mean_squared_error(y_test,preds)

8463.920713454827

In [138]:
is_private = df['room_type'] == 0


In [139]:
private_df = df[is_private]

In [140]:
private_df

host_id  neighbourhood_group  neighbourhood  latitude  longitude  \
0        266763                    0              0   1.44255  103.79580   
1        227796                    1              1   1.33235  103.78521   
2        266763                    0              0   1.44246  103.79667   
3        367042                    2              2   1.34541  103.95712   
4        367042                    2              2   1.34567  103.95963   
5        367042                    2              2   1.34702  103.96103   
6        367042                    2              2   1.34348  103.96337   
7       1017645                    2              3   1.32304  103.91363   
8       1017645                    2              3   1.32458  103.91163   
9       1017645                    2              3   1.32461  103.91191   
10      1439258                    1              4   1.28875  103.80814   
11      1439258                    1              4   1.28837  103.81099   
12       367042                    2              2   1.34561  103.95984   
13      1521514                    1              5   1.31125  103.83816   
14      1439258                    1              4   1.28976  103.80896   
15      1439258                    1              4   1.28677  103.81244   
16      1439258                    1              4   1.28537  103.81087   
17       367042                    2              2   1.34943  103.95951   
18      1759905                    1              6   1.31420  103.90232   
19      1521514                    1              5   1.31150  103.83759   
20      1521514                    1              5   1.31159  103.83805   
21      1975201                    1              7   1.29345  103.83562   
22       367042                    2              2   1.34838  103.95920   
23      2386154                    2              2   1.34816  103.93238   
24      1030128                    3              8   1.34135  103.71139   
26      3212572                    1              9   1.30109  103.85234   
27      1289033                    1              1   1.31016  103.79853   
29      3824517                    4             11   1.36743  103.87288   
31      1584407                    1             12   1.30377  103.89956   
32      3981231                    4             11   1.35001  103.87161   
...         ...                  ...            ...       ...        ...   
7848    2413412                    1             19   1.31004  103.86323   
7849   39207304                    1             12   1.30652  103.90238   
7850   39207304                    1             12   1.30489  103.90397   
7851   39207304                    1             12   1.30642  103.90217   
7852    8948251                    1              6   1.31518  103.88065   
7853   12352775                    1             17   1.29613  103.82995   
7854   12352775                    1             17   1.29481  103.83060   
7855   12352775                    1             17   1.29676  103.82982   
7863    6632570                    0              0   1.44059  103.79904   
7866  287174284                    1             15   1.28495  103.84495   
7867  288546201                    3             32   1.30650  103.76732   
7868  287739845                    4             25   1.38759  103.85524   
7870   12352775                    1             17   1.29636  103.82983   
7871   12352775                    1             17   1.29454  103.83046   
7872  287739845                    4             25   1.38919  103.85548   
7873  288567551                    1             23   1.28796  103.84494   
7876    8948251                    1             19   1.31163  103.86090   
7877    6632570                    0              0   1.44052  103.79784   
7880  262337792                    1              7   1.29560  103.83803   
7882    8948251                    1             19   1.31004  103.86208   
7886  259978610                    2              2   1.

In [178]:
X = private_df.drop("price",axis=1).values
y = private_df["price"].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=66)

In [179]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)
preds = model.predict(X_test)

In [180]:
preds

array([228.17430137, 200.43283504, 169.24421001, ..., 175.93163076,
       177.6339381 , 214.1981388 ])

In [181]:
y_test

array([147,  28, 318, ..., 281, 260, 165])

In [182]:
mean_squared_error(y_test,preds)

8460.703585310932

In [183]:
from sklearn.linear_model import LinearRegression,BayesianRidge
model = RandomForestRegressor(n_estimators=110, max_depth=10)
model.fit(X_train,y_train)
preds = model.predict(X_test)

In [184]:
list(preds)

[166.4163240769871,
 41.86351783642607,
 259.1550102383557,
 77.94366128999413,
 220.3980438295193,
 73.65948659999306,
 46.3135399772303,
 341.9296499496109,
 187.06265845115072,
 224.97004472626674,
 199.41781983992988,
 51.681813237155204,
 309.6001708332096,
 75.21518114973846,
 179.07267667436642,
 294.5895641811667,
 112.91891831271086,
 110.20687851734328,
 56.01505088870683,
 129.18837266159917,
 184.2775001468436,
 292.27532616701615,
 212.78116581464974,
 42.24578980950448,
 101.59320417956768,
 106.95901709040159,
 113.31279254898388,
 103.4756530936945,
 65.93431440968001,
 48.110559416746725,
 231.7803676375533,
 171.51537377753516,
 53.63725186280119,
 188.0925970290043,
 165.103827128947,
 84.29453620233095,
 33.48427744978607,
 70.23325718115245,
 164.358768451833,
 65.08844988504475,
 227.4255643417921,
 58.127118248901105,
 198.4207526808127,
 228.63169493567673,
 344.5648583432891,
 191.8612220852569,
 180.2250333267137,
 74.75406882861333,
 127.48399372788944,
 220.

In [185]:
list(y_test)

[147,
 28,
 318,
 50,
 228,
 49,
 32,
 108,
 194,
 190,
 218,
 51,
 200,
 49,
 100,
 453,
 150,
 99,
 40,
 56,
 131,
 114,
 149,
 42,
 99,
 69,
 65,
 81,
 50,
 69,
 287,
 125,
 50,
 139,
 89,
 118,
 50,
 79,
 100,
 35,
 287,
 81,
 200,
 139,
 368,
 250,
 131,
 137,
 119,
 178,
 319,
 181,
 44,
 58,
 300,
 171,
 199,
 115,
 44,
 258,
 249,
 56,
 118,
 129,
 37,
 200,
 181,
 428,
 51,
 25,
 37,
 99,
 194,
 387,
 37,
 200,
 62,
 200,
 87,
 181,
 58,
 99,
 250,
 69,
 81,
 239,
 150,
 110,
 81,
 215,
 100,
 90,
 76,
 43,
 69,
 131,
 56,
 26,
 151,
 342,
 90,
 119,
 69,
 368,
 29,
 165,
 31,
 258,
 131,
 114,
 140,
 160,
 62,
 57,
 108,
 40,
 32,
 150,
 87,
 137,
 240,
 158,
 153,
 35,
 125,
 104,
 110,
 158,
 94,
 110,
 60,
 187,
 300,
 110,
 110,
 460,
 19,
 119,
 90,
 128,
 381,
 42,
 37,
 200,
 94,
 160,
 85,
 214,
 31,
 185,
 35,
 40,
 300,
 82,
 50,
 208,
 56,
 222,
 108,
 181,
 189,
 68,
 87,
 94,
 49,
 99,
 87,
 300,
 35,
 115,
 122,
 90,
 110,
 72,
 85,
 50,
 119,
 181,
 81,
 78,
 3

In [186]:
mean_squared_error(y_test,preds)

3892.3366245879347

In [187]:
yl = list(y_test)
pl = list(preds)
for i in range(len(yl)):
    print((yl[i],pl[i]))

(147, 166.4163240769871)
(28, 41.86351783642607)
(318, 259.1550102383557)
(50, 77.94366128999413)
(228, 220.3980438295193)
(49, 73.65948659999306)
(32, 46.3135399772303)
(108, 341.9296499496109)
(194, 187.06265845115072)
(190, 224.97004472626674)
(218, 199.41781983992988)
(51, 51.681813237155204)
(200, 309.6001708332096)
(49, 75.21518114973846)
(100, 179.07267667436642)
(453, 294.5895641811667)
(150, 112.91891831271086)
(99, 110.20687851734328)
(40, 56.01505088870683)
(56, 129.18837266159917)
(131, 184.2775001468436)
(114, 292.27532616701615)
(149, 212.78116581464974)
(42, 42.24578980950448)
(99, 101.59320417956768)
(69, 106.95901709040159)
(65, 113.31279254898388)
(81, 103.4756530936945)
(50, 65.93431440968001)
(69, 48.110559416746725)
(287, 231.7803676375533)
(125, 171.51537377753516)
(50, 53.63725186280119)
(139, 188.0925970290043)
(89, 165.103827128947)
(118, 84.29453620233095)
(50, 33.48427744978607)
(79, 70.23325718115245)
(100, 164.358768451833)
(35, 65.08844988504475)
(287, 227

In [189]:
model = GradientBoostingRegressor(n_estimators=110, max_depth=10)
model.fit(X_train,y_train)
preds = model.predict(X_test)

In [190]:
mean_squared_error(y_test,preds)

4200.086158811532

In [191]:
is_private = df['number_of_reviews'] > 1
private_df = df[is_private]

In [177]:
private_df

host_id  neighbourhood_group  neighbourhood  latitude  longitude  \
1        227796                    1              1   1.33235  103.78521   
2        266763                    0              0   1.44246  103.79667   
3        367042                    2              2   1.34541  103.95712   
4        367042                    2              2   1.34567  103.95963   
5        367042                    2              2   1.34702  103.96103   
6        367042                    2              2   1.34348  103.96337   
7       1017645                    2              3   1.32304  103.91363   
8       1017645                    2              3   1.32458  103.91163   
9       1017645                    2              3   1.32461  103.91191   
10      1439258                    1              4   1.28875  103.80814   
11      1439258                    1              4   1.28837  103.81099   
12       367042                    2              2   1.34561  103.95984   
13      1521514                    1              5   1.31125  103.83816   
14      1439258                    1              4   1.28976  103.80896   
15      1439258                    1              4   1.28677  103.81244   
16      1439258                    1              4   1.28537  103.81087   
17       367042                    2              2   1.34943  103.95951   
19      1521514                    1              5   1.31150  103.83759   
20      1521514                    1              5   1.31159  103.83805   
21      1975201                    1              7   1.29345  103.83562   
22       367042                    2              2   1.34838  103.95920   
24      1030128                    3              8   1.34135  103.71139   
25      2996022                    1              1   1.33171  103.79383   
27      1289033                    1              1   1.31016  103.79853   
30      3919513                    2              3   1.30792  103.92287   
31      1584407                    1             12   1.30377  103.89956   
32      3981231                    4             11   1.35001  103.87161   
34      4030859                    1             14   1.34143  103.84945   
35      2413412                    1             15   1.28315  103.84213   
39      1439258                    1              4   1.28909  103.80749   
...         ...                  ...            ...       ...        ...   
7443  276695204                    4             18   1.36765  103.89828   
7446  223971227                    1             15   1.28116  103.84417   
7447  223971227                    1             15   1.28076  103.84563   
7450  223971227                    1             15   1.28133  103.84417   
7460    8527085                    1              5   1.30576  103.84656   
7461   43416974                    1             10   1.30188  103.79698   
7462    8527085                    1              5   1.30597  103.84737   
7464    8527085                    1              9   1.30665  103.84736   
7466    8527085                    1              9   1.30771  103.84712   
7479  264191580                    1             19   1.31608  103.85376   
7482   20883050                    1              6   1.30964  103.88176   
7483  277268084                    3             26   1.36065  103.76277   
7488  276843600                    1              7   1.29816  103.84230   
7490  277326066                    1              6   1.31161  103.88476   
7496  189326474                    1              7   1.29803  103.83783   
7498  189326474                    1             27   1.29901  103.84576   
7504   23145293                    1              4   1.26569  103.81606   
7505  278109833                    1             20   1.31976  103.84863   
7509   37379638                    0             35   1.43349  103.84476   
7510   55611829                    1             20   1.31841  103.84739   
7514   37379638                    0             35   1.

In [291]:
samples = [[0, 0, 4,2], [1,4, 0, 0], [1,0, 0, 1]]
neigh = NearestNeighbors(2, 0.4)
neigh.fit(samples) 

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=1, n_neighbors=2, p=2, radius=0.4)

In [293]:
neigh.kneighbors([[0, 0, 2,1.3]], 1, return_distance=True)

(array([[2.11896201]]), array([[0]]))

In [306]:
df2 = pd.DataFrame(np.array([[1, 2, 3],[0, 4, 3], [4, 5, 6], [7, 8, 9]]), columns=['a', 'b', 'c'])

In [307]:
df2

a  b  c
0  1  2  3
1  0  4  3
2  4  5  6
3  7  8  9

In [321]:
X = df2.values
neigh = NearestNeighbors()
neigh.fit(X) 

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=1, n_neighbors=5, p=2, radius=1.0)

In [322]:
X.shape

(4, 3)

In [310]:
neigh.kneighbors([[0, 2,1.3]], 1, return_distance=True)

(array([[1.97230829]]), array([[0]]))

In [320]:
y

array([2.2779600e+05, 1.0000000e+00, 1.0000000e+00, 1.3323500e+00,
       1.0378521e+02, 0.0000000e+00, 8.1000000e+01, 9.0000000e+01,
       1.8000000e+01, 2.8000000e-01, 1.0000000e+00, 3.6500000e+02])

In [28]:
df.head()

host_id  neighbourhood_group  neighbourhood  latitude  longitude  \
0   266763                    0              0   1.44255  103.79580   
1   227796                    1              1   1.33235  103.78521   
2   266763                    0              0   1.44246  103.79667   
3   367042                    2              2   1.34541  103.95712   
4   367042                    2              2   1.34567  103.95963   

   room_type  price  minimum_nights  number_of_reviews  reviews_per_month  \
0          0     83             180                  1               0.01   
1          0     81              90                 18               0.28   
2          0     69               6                 20               0.20   
3          0    206               1                 14               0.15   
4          0     94               1                 22               0.22   

   calculated_host_listings_count  availability_365  
0                               2               365  
1                               1               365  
2                               2               365  
3                               9               353  
4                               9               355

In [101]:
df['latitude'] = df['latitude']*100
df['longitude'] = df['longitude']*100

In [137]:
df.head()

neighbourhood_group  neighbourhood  latitude  longitude  room_type  price  \
0                    0              0   1.44255  103.79580          0     83   
1                    1              1   1.33235  103.78521          0     81   
2                    0              0   1.44246  103.79667          0     69   
3                    2              2   1.34541  103.95712          0    206   
4                    2              2   1.34567  103.95963          0     94   

   minimum_nights  number_of_reviews  reviews_per_month  \
0             180                  1               0.01   
1              90                 18               0.28   
2               6                 20               0.20   
3               1                 14               0.15   
4               1                 22               0.22   

   calculated_host_listings_count  availability_365  
0                               2               365  
1                               1               365  
2                               2               365  
3                               9               353  
4                               9               355

In [64]:
df.drop("host_id", axis=1,inplace=True)

In [76]:
df.drop("neighbourhood_group", axis=1,inplace=True)
df.drop("neighbourhood", axis=1,inplace=True)

In [31]:
knn_df = df[["latitude","longitude","room_type","price","minimum_nights"]].copy()

In [32]:
knn_df.head()

latitude  longitude  room_type  price  minimum_nights
0   1.44255  103.79580          0     83             180
1   1.33235  103.78521          0     81              90
2   1.44246  103.79667          0     69               6
3   1.34541  103.95712          0    206               1
4   1.34567  103.95963          0     94               1

In [33]:
knn_df['latitude'] = knn_df['latitude']*1000
knn_df['longitude'] = knn_df['longitude']*1000
#knn_df['room_type'] = knn_df['room_type']*10

In [35]:
is_private =knn_df['room_type'] ==0
k_df = knn_df[is_private].copy()

In [36]:
k_df.head()

latitude  longitude  room_type  price  minimum_nights
0   1442.55  103795.80          0     83             180
1   1332.35  103785.21          0     81              90
2   1442.46  103796.67          0     69               6
3   1345.41  103957.12          0    206               1
4   1345.67  103959.63          0     94               1

In [37]:
k_df = k_df.reset_index()

In [38]:
k_df.drop("index", axis=1,inplace=True)

In [39]:
import numpy as np
from sklearn.neighbors import NearestNeighbors
X = k_df.values
model = NearestNeighbors(10,100, metric='manhattan')
model.fit(X) 

NearestNeighbors(algorithm='auto', leaf_size=30, metric='manhattan',
         metric_params=None, n_jobs=1, n_neighbors=10, p=2, radius=100)

In [40]:
example = [[ 1,1,1.33235,103.78521,0,81,90,18,0.28,1,365]]
y = y.reshape(1,-1)
#example = np.array(example)
model.kneighbors([[1332.35,103785.21,0,81,90]], 5, return_distance=True)

(array([[1.45519152e-11, 2.49200000e+01, 3.36600000e+01, 3.40100000e+01,
         3.72100000e+01]]), array([[   1, 2264, 1740,  314,  282]]))

In [41]:
k_df.loc[1]

latitude            1332.35
longitude         103785.21
room_type              0.00
price                 81.00
minimum_nights        90.00
Name: 1, dtype: float64

In [42]:
k_df.loc[2264]

latitude            1332.55
longitude         103790.93
room_type              0.00
price                100.00
minimum_nights        90.00
Name: 2264, dtype: float64

In [43]:
k_df.loc[1740]

latitude            1318.18
longitude         103786.70
room_type              0.00
price                 99.00
minimum_nights        90.00
Name: 1740, dtype: float64

In [270]:
k_df.loc[314]

latitude            1344.86
longitude         103768.71
room_type              0.00
price                 76.00
minimum_nights        90.00
Name: 314, dtype: float64